const STICKY = '[STICKY]'
const IS_STICKY = `${STICKY} Is Sticky`
const IS_ACTIVE = `${STICKY} Is Active Link`
const ENTER_TRANSITION = `${STICKY} Enter Transition`
const EXIT_TRANSITION = `${STICKY} Exit Transition`
const DEFAULT = `${STICKY} Default`
const MAKE_STICKY = `${STICKY} MAKE_STICKY`
const BREAK_STICKY = `${STICKY} BREAK_STICKY`
const IS_DRAGGING = `${STICKY} IS_DRAGGING`

export default {
  IS_STICKY,
  ENTER_TRANSITION,
  EXIT_TRANSITION,
  IS_ACTIVE,
  DEFAULT,
  MAKE_STICKY,
  BREAK_STICKY,
  IS_DRAGGING
}
